spring:
  application:
    name: "dRAGon"
server:
  port: 1985
springdoc:
  swagger-ui:
    path: "/api/swagger-ui.html"
  api-docs:
    path: "/api/docs"
org:
  jobrunr:
    background-job-server:
      enabled: false
    job-scheduler:
      enabled: false
    dashboard:
      enabled: false
dragon:
  data:
    path: ":temp:"
    db: ":memory:"