spring:
  application:
    name: "dRAGon"
server:
  port: 1985
springdoc:
  swagger-ui:
    path: "/api/swagger-ui.html"
  api-docs:
    path: "/api/docs"
org:
  jobrunr:
    background-job-server:
      enabled: true
      poll-interval-in-seconds: 5 # Check for new work every 5 seconds
    job-scheduler:
      enabled: true
    jobs:
      default-number-of-retries: 0 # Number of retries for a failing job
dragon:
  data:
    path: ":temp:"
    db: ":memory:"