/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about',
      localIcon: 'mdi--library-outline',
      order: 10
    }
  },
  {
    name: 'help',
    path: '/help',
    component: 'layout.base$view.help',
    meta: {
      title: 'help',
      i18nKey: 'route.help',
      order: 99,
      localIcon: 'majesticons--question-circle-line',
      href: 'https://dragon.okinawa'
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      localIcon: 'mdi--monitor-dashboard',
      order: 1,
      keepAlive: true
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'infrastructure',
    path: '/infrastructure',
    component: 'layout.base',
    meta: {
      title: 'infrastructure',
      i18nKey: 'route.infrastructure',
      localIcon: 'mdi--land-fields',
      order: 2,
      roles: ['R_ADMIN']
    },
    children: [
      {
        name: 'infrastructure_silo-detail',
        path: '/infrastructure/silo-detail/:id',
        component: 'view.infrastructure_silo-detail',
        meta: {
          title: 'infrastructure_silo-detail',
          i18nKey: 'route.infrastructure_silo-detail',
          roles: ['R_ADMIN'],
          activeMenu: 'infrastructure_silo-list',
          hideInMenu: true
        }
      },
      {
        name: 'infrastructure_silo-list',
        path: '/infrastructure/silo-list',
        component: 'view.infrastructure_silo-list',
        meta: {
          title: 'infrastructure_silo-list',
          i18nKey: 'route.infrastructure_silo-list',
          localIcon: 'mdi--silo-outline',
          order: 1,
          roles: ['R_ADMIN'],
          keepAlive: true
        }
      }
    ]
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      hideInMenu: true,
      roles: ['R_ADMIN'],
      keepAlive: true
    }
  }
];
