site_url: https://dragon.okinawa
site_name: dRAGon
docs_dir: src
copyright: dRAGon &copy; 2024<br />Like my work? <a href="https://github.com/sponsors/isontheline">Sponsors</a> and <a href="https://www.buymeacoffee.com/isontheline">Coffees</a> are welcome!
theme:
  name: material
  custom_dir: overrides
  logo: img/dragon_okinawa_icon.png
  favicon: favicon.ico
  font: false
  palette:
    scheme: preference
  features:
    - navigation.tabs
extra_css:
  - css/extra.css?20240501
extra_javascript:
  - js/extra.js?20240501
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/isontheline/dragon
    - icon: fontawesome/solid/heart
      link: https://github.com/sponsors/isontheline
    - icon: fontawesome/solid/mug-saucer
      link: https://www.buymeacoffee.com/isontheline
plugins:
  - search
  - git-revision-date-localized:
      type: date
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - footnotes