name: Build dRAGon Project

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dRAGon sources
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Lint Frontend
        run: gradle npmInstall build npmLint
  build:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout dRAGon sources
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build dRAGon
        run: gradle build
