name: Build dRAGon Project
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
      - name: Test dRAGon
        run: gradle npmInstall npmLint test
      - name: Create Release
        run: gradle createRelease
      - name: Set Frontend Version
        run: npm version from-git --no-git-tag-version --prefix frontend
      - name: Set Docs Version
        run: npm version from-git --no-git-tag-version --prefix docs
      - name: Build dRAGon
        run: gradle build -Pversion=$(gradle cV -q -Prelease.quiet)
      - name: Push Release
        if: github.ref == 'refs/heads/main'
        run: gradle pushRelease
