name: Build dRAGon Project
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
      - name: Test dRAGon
        run: gradle npmInstall npmLint test
      - name: Create Release
        run: gradle createRelease
      - name: Build dRAGon
        run: gradle build
      - name: Push Release
        if: github.ref == 'refs/heads/main'
        run: gradle pushRelease
